package com.company;

// video link ----> https://youtu.be/N3Xu1rO6feY?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q
class Cylinder {

  private  int radi;
  private  int Height;
//FOR PROBLEM 3 //Constructor

    public Cylinder(int radi, int height) {
        this.radi = radi;
        Height = height;
    }

    //FOR PROBLEM 1
    //Getter ans setter generated by code>Generate>Getter and Setter.
    public int getRadi() {
        return radi;
    }

    public void setRadi(int radi) {
        this.radi = radi;
    }

    public int getHeight() {
        return Height;
    }

    public void setHeight(int height) {
        Height = height;
    }
    //Getter and setter made by self
   /* public int getradi(){
        System.out.println("the radius of cylinder is :");
        return radi;
    }
    public void setRadi(int radi){
        this.radi= radi;
    }

    public int getHeight(){
        System.out.println("the Height of cylinder is :");
        return Height;
    }
    public void setHeight(int Height){
        this.Height= Height;
    }  */

//FOR PROBLEM 2
         public double VolumeOfCylinder(){
             return 3.142*radi*radi*Height;  // in place of 3.142 which is apprx value of PI we can use Math.PI which gives more accurate value of PI
    }

    public double surfaceArea(){
             return 2*3.142*radi*radi + 2*3.142*radi*Height;
    }
    }

//FOR PROBLEM 4
class Rectangle1 {
    int length;
    int breadth;

    public Rectangle1() {
        this.length = 4;
        this.breadth = 7;
    }

    public Rectangle1(int length, int breadth) {
        this.length = length;
        this.breadth = breadth;
    }

    public int getLength() {
        return length;
    }

    public int getBreadth() {
        return breadth;
    }
}
public class cwh_44_PracticeSetCH9 {
    public static void main(String[] args) {

        //Problem 1
  //      Cylinder cy = new Cylinder(5, 10);
      /*  cy.radi=10;
        cy.Height=5;
        System.out.println("The radius of cylinder is:" +cy.radi);
        System.out.println("The Height of cylinder is:" + cy.Height);  */

    /*    cy.setHeight(10);
        int h = cy.getHeight();
        System.out.print("The height of cylinder is :");
        System.out.println(h);
        //or
        System.out.println(cy.getHeight());

        cy.setRadi(5);
        int r = cy.getRadi();
        System.out.print("The radius of cylinder is :");
        System.out.println(r);

        //Problem 2
        System.out.println("The volume of cylinder is :" + cy.VolumeOfCylinder());
        System.out.println("The surface area of cylinder is :" + cy.surfaceArea());

        //Problem 3
        System.out.println("using constructor : ");
        // in place of problem 1 by using constructor we can simply write or code
        System.out.print("The height of cylinder is :");
        System.out.println(cy.getHeight());


        System.out.print("the radius of cylinder is :");
        System.out.println(cy.getRadi()); */

        // Problem 4
       Rectangle1 rect = new Rectangle1(12,22);
        System.out.println(rect.getLength());
        System.out.println(rect.getBreadth());


    }
}
